export const jokeArray =
[
    "I farted into my wallet. Now I have gas money.",
    "German sausage jokes are the wurst.",
    "My wife said that I should do lunges to stay in shape. I told that that would be a huge step forward.",
    "I was singing in the shower & got soap in my mouth. Then it was a soap opera.",
    "How do you track Will Smith in the snow? You follow the fresh prints",
    "April showers bring may flowers. May flowers bring pilgrims",
    "Seagulls flow over the sea. Bagels fly over the bay.",
    "I only know 25 letters. I don't know y",
    "How does the moon cut it's hair? Eclipse it.",
    "If you're cold, stand in the corner. It's always 90 degrees",
    "I asked my dog what 2 minus 2 was. He said nothing.",
    "I don't know what the best thing about Switzerland is, but their flag is a big plus",
    "I learned to make a banana split at Sundae School",
    "Where do ships go when they get sick? The dock",
    "I don't trust trees. They seem kind of shady",
    "My wife said that I don't have a sense of direction. I got so mad I up and right the house.",
    "I have a bunch of egg jokes that will crack you up.",
    "I don't trust stairs. They're always up to something",
    "What do you call someone with no body and no nose? Nobody knows.",
    "I heard a rumor about butter but I didn't want to spread it.",
    "The bicycle couldn't stand up because it was too tired",
    "I got fired from the banana factory for throwing away all the bent ones.",
    "If a nose is 12 inches long, it would be a foot.",
    "The graveyard is popular. People are dying to get in.",
    "I called a lemon on the phone. He said, 'Yellow!'",
    "Eggs like to drive a Yolkswagon",
    "My wife asked me to put the cat out. I didn't even know it was on fire.",
    "I had a taco for dinner. It insisted I say grace first. 'Lettuce pray'",
    "I have a dentist appointment at tooth hurty.",
    "Skeletons are cowards. They have no guts.",
    "How many tickles does it take to make an octopus laugh? Ten tickles",
    "What do you call cheese that isn't yours? Nacho cheese",
    "What concert costs 45 cents? Fifty cent featuring Nickleback.",
    "Bees brush their hair with a honey comb",
    "You make a tissue dance by putting a little boogie in it",
    "Math books are always sad because they have a lot of problems",
    "I know a joke about boxing but I forget the punchline",
    "How does a penguin build a house? Igloos it together.",
    "How did Harry Potter get down the hill? Walking. JK! Rowling",
    "I used to be addicted to soap, but I am clean now.",
    "I not addicted to brake fluid. I can stop any time.",
    "When two vegans argue, is it still called a beef?",
    "I ordered a chicken and an egg from Amazon. I'll let you know.",
    "The waiter asked if I wanna box for left overs. I told him we could wrestle for them.",
    "My cars muffler didn't work this morning. I think it was exhausted.",
    "I trust my fingers. I can always count on them.",
    "My toddler was charged with resisting a rest.",
    "I had a dream I was swimming in an orange soda ocean. It was a Fanta sea.",
    "Corduroy pillows are very popular now. They are starting to make headlines.",
    "I was fired from the canned juice factory because I couldn't concentrate.",
    "I tried to catch the fog yesterday, but I mist.",
    "I made a pencil with two erasers. It was pointless.",
    "I'm reading a book about antigravity. I can't put it down.",
    "The guy that invented the knock knock joke won the no bell prize.",
    "I didn't think I'd like having a beard, but it grew on me.",
    "I never use my vacuum cleaner. It sucks. It was just gathering dust.",
    "I put on a neck brace 5 years ago and I haven't looked back since.",
    "I never picked my nose. I was born with it.",
    "What's brown and sticky? A stick.",
    "Elephants that don't matter are Irrelephant",
    "Pampered cows give spoiled milk",
    "The best smelling insects are deodor-ants",
    "I used to be a personal trainer, but I put in my two weak notice.",
    "I fell in love with doing back flips. I was heals over head for them.",
    "It takes guts to be an organ donor.",
    "If you see a crime at the Apple store, does that make you an iWitness?",
    "I'm so good at sleeping I can do it with my eyes closed.",
    "I was going to tell a time travelling joke, but you guys didnt' get it.",
    "A fake noodle is an impasta.",
    "I made a belt out of watches. It was a waste of time.",
    "I ran over a strawberry. It caused a traffic jam.",
    "Two monkeys that share an Amazon account are Prime Mates",
    "My pony had a sore throat. It was a little hoarse.",
    "Math teachers go on vacation to Times Square",
    "Santa doesn't get charged for parking his sleigh. It's always on the house.",
    "Mountains aren't just funny. They are hill areas.",
    "Clouds wear thunderwear",
    "Piggy banks are so smart because they have common cents.",
    "There was a circus fire in town. It was in tents.",
    "Can February March? No but April May",
    "I had a joke about paper but it was terrible.",
    "I was just watching a live stream of a fishing tournament.",
    "I was so excited about Spring I wet my plants.",
    "I'm not going to tell you a joke about pizza. It's too cheesy.",
    "I don't trust atoms. They make up everything.",
    "Chad's face.",
    "I bought pants made out of velcro. They were a total ripoff.",
    "Astronauts drink at the space bar.",
    "I don't play soccer to get famous. I just do it for kicks.",
    "Elevator jokes are classic because they work on so many levels.",
    "The coffee cup called the police to report a mugging",
    "What did the fish say when he hit the wall? Dam.",
    "Is the pool safe for diving? Deep ends.",
    "I was sitting on the beach. I asked the ocean, 'Who are you waving at?'",
    "The bank teller asked if I wanted to know my balance. I told her I hadn't fallen over for some time now.",
    "My daughter asked, 'Can I have a book mark?'. I was so upset. She knows my name is Rob.",
    "Gonorrhea would have been a great name for diarrhea medicine.",
    "National anthems are all country music.",
    "Dry Erase Boards are a remarkable invention.",
    "I took my daughter to work but she got upset because she couldn't find any of the clowns I say I work with.",
    "How can you decide if a tree is a Dogwood? By it's bark.",
    "My wife and daughter look like twins but they were separated at birth.",
    "I ordered a dozen bees from PetSmart but they gave me 13. One was a free bee.",
    "Halloween is amazing because all the hornets wear ghost costumes. I love boo bees.",
    "My wife said, 'You haven't listened to a single word I said', which is a weird way to start a conversation.",
    "I confused the words 'jacuzzi' and 'yakuza'. Now I'm in hot water with the Japanese mafia.",
    "I got an email from a company that can read maps backwards. I was like, 'that is just spam'.",
    "My wife was watching a movie and yelled out, 'Don't Go In There! Don't go into the church!'. It was our wedding video.",
    "I got hurt playing Peek-A-Boo. They took me to the I.C.U.",
    "My landlord asked if he could talk about my heating bill. I told him 'My door is always open.'",
    "My grandpa died because we couldn't remember his blood type. Even as he was slipping away he told me to 'be positive'",
    "What has five toes but isn't your foot? My foot.",
    "The average person is really mean",
    "My daughter wouldn't quit chewing on electrical cords so I had to ground her.",
    "My friend came over to my house and asked what's upstairs. I told him that stairs don't talk.",
    "The quality of jokes about Jack and Jill are really just going down hill.",
    "I called Ameritrade customer support and they told me to hold.",
    "What kind of milk is that? Soy milk. Hola Milk! Soy dad.",
    "I say my neighbor digging three deep holes. I was like 'well, well, well.'"

];